### ISSUE TITLE
Use std for hmac

### ISSUE THREAD

**Issue by lucacasonato** [lucacasonato/deno_aws_sign_v4#3]
https://denopkg.com/chiefbiiko/hmac@v1.0.2/mod.ts should be replaced with an `hmac` implementation from std once https://github.com/denoland/deno/issues/7297 is resolved.

**Comment by danopia** [comment]
Is there a reason to not use `HmacSha256` from `/std/hash/sha256.ts`? I see that https://github.com/denoland/deno_std/issues/653 is still open, but it's for WebAssembly implementations and has gone a bit stale. The TypeScript implementation in std has been working fine for me and I could write up a PR here to use it.

**Comment by lucacasonato** [comment]
Sure, PR would be welcome. The newest ultimate plan is to use crypto once that lands :-)
